// Event types generated by writing a value to the PLC (POST /tags/{key}/write
// in api/router.py) — distinct from system alarms generated by alarms/engine.py
// from live tag/connection state. Kept in one place so Alarms & Events and
// Audit Log filter against the exact same list.
export const COMMAND_EVENT_TYPES = ["COMMAND_WRITE", "COMMAND_REJECTED", "COMMAND_FAILED"];
