// Event types generated by writing a value to the PLC (POST /tags/{key}/write
// in api/router.py), or by an insufficient-role request being blocked
// (auth/deps.py::require_role) — distinct from system alarms generated by
// alarms/engine.py from live tag/connection state. Kept in one place so
// Alarms & Events and Audit Log filter against the exact same list.
export const COMMAND_EVENT_TYPES = ["COMMAND_WRITE", "COMMAND_REJECTED", "COMMAND_FAILED", "COMMAND_RATE_LIMITED", "ACCESS_DENIED"];
